# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSProjectTemplate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSProjectTemplate
	pod 'IQKeyboardManagerSwift'
	pod 'SDWebImage'
	pod 'Alamofire'
	pod 'AlamofireObjectMapper'
	pod 'M13ProgressSuite'
	pod 'SwiftyExtension'
	pod 'SwiftValidator', :git => 'https://github.com/jpotts18/
SwiftValidator.git', :branch => 'master'
	pod 'SZTextView', '~> 1.2'

  target 'iOSProjectTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSProjectTemplateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
